### ISSUE TITLE
describe on remote source.coop files not working

### ISSUE THREAD

**Issue by cholmes** [planetlabs/gpq#105]
I've only tried on source cooperative, so there's some chance it's just a problem with those. But whenever I try describe or validate on a remote url it doesn't work, with the same error message:

```
% gpq describe https://beta.source.coop/cholmes/overture/geoparquet-country-quad-hive/country_iso=JM/Jamaica.parquet
gpq: error: command.DescribeCmd.Run(): failed to read 
"https://beta.source.coop/cholmes/overture/geoparquet-country-quad-hive/country_iso=JM/Jamaica.parquet" 
as parquet: parquet: file is smaller than indicated metadata size
```

I'm on 0.20.0

**Comment by tschaub** [comment]
https://beta.source.coop/cholmes/overture/geoparquet-country-quad-hive/country_iso=JM/Jamaica.parquet is an html page instead of a parquet file.

Give it a try with the download url (on a phone and can’t copy it right now)

**Comment by cholmes** [comment]
Ah, thanks. Pretty sure they changed their interface - I was used to having that link be the download one. Working now.

**Comment by tschaub** [comment]
Would be nice to improve the error message in this case.
