### ISSUE TITLE
support newline delimited geojson? 

### ISSUE THREAD

**Issue by cholmes** [planetlabs/gpq#202]
Maybe I'm doing something wrong, but I'm doing `planet data search SkySatCollect | gpq convert --from geojson --to geoparquet > gpq-out.parquet` and I just get one feature. Planet's API emits [newline delimited geojson](https://stevage.github.io/ndgeojson/). It'd be great to be able to stream from it and other api's, as collecting all the new lined geojsons into a single geojson can take a lot of memory.

**Comment by tschaub** [comment]
Fixed by #231.
