### ISSUE TITLE
gpq convert creates invalid file

### ISSUE THREAD

**Issue by m-mohr** [planetlabs/gpq#45]
I used gpq convert to create a geoparquet file from a parquet file:
`gpq convert C:\Dev\rapidai4eo\stac-v1.0\rapidai4eo_v1_source_pf\pf.parquet rapidai4eo_v1_source_pf_snappy.geoparquet --compression="snappy"`
Afterwards, I ran gpq validate on it and the new file is invalid.
It is missing the geoparquet version number (empty string).

v0.11.0 on Windows 10

**Comment by m-mohr** [comment]
I don't really understand Go, but I suspect that maybe above https://github.com/planetlabs/gpq/blob/main/internal/geoparquet/geoparquet.go#L404 the Version number must be set?

**Comment by tschaub** [comment]
@m-mohr - this should be fixed now, but I'd like to validate it before cutting a release.  Do you happen to have that `C:\Dev\rapidai4eo\stac-v1.0\rapidai4eo_v1_source_pf\pf.parquet` file around so I could test it?

**Comment by m-mohr** [comment]
Thanks, Tim! I don't think I have it anymore, but I can also only check once I'm back from the STAC sprint, i.e. next week Wed. So maybe just go ahead with the release?!

**Comment by tschaub** [comment]
This should be fixed in the latest release.  Please reopen if you find an issue.
