### ISSUE TITLE
Convert: Compression toggle doesn't work?

### ISSUE THREAD

**Issue by m-mohr** [planetlabs/gpq#46]
I ran the following commands:
- `gpq convert C:\Dev\rapidai4eo\stac-v1.0\rapidai4eo_v1_source_pf\pf.parquet rapidai4eo_v1_source_pf_snappy.geoparquet`
- `gpq convert C:\Dev\rapidai4eo\stac-v1.0\rapidai4eo_v1_source_pf\pf.parquet rapidai4eo_v1_source_pf_snappy.geoparquet --compression="snappy"`

The files I get are exactly the same. I suspect both files are gzip compressed and the compression parameter was not taken into account.

**Comment by tschaub** [comment]
Thanks for the report.  I noticed the same recently and meant to ticket it.  The compression is not taken into account when converting Parquet to GeoParquet, but it is when converting GeoJSON to GeoParquet.  There are other issues to work out with the Parquet -> GeoParquet transform (e.g. when going from WKT to WKB, the schema is not updated).  This issue can be addressed along with the other transform issues.
