### ISSUE TITLE
describe: report about compression method

### ISSUE THREAD

**Issue by m-mohr** [planetlabs/gpq#47]
I think it would be interesting (e.g. for investigating #46) to report the compression method in `gpq describe`

**Comment by tschaub** [comment]
I added output about the compression to the `describe` output.  This is a simplified view of the actual compression.  In a Parquet file, compression can vary per column and per row group.  The `describe` output only summarizes the compression levels in the first row group.  For nested fields, the `--format json` output includes the compression for all fields.  The non-JSON output only describes the top level logical fields.
