### ISSUE TITLE
Issue converting a complicated GeoParquet file

### ISSUE THREAD

**Issue by cholmes** [planetlabs/gpq#82]
I got an error when running `gpq convert AR.parquet Argentina-overture.parquet` - was hoping it'd upgrade to 1.0.0 (and I could adjust row groups after I got the initial one working. AR.parquet is from https://data.source.coop/cholmes/overture/geoparquet-country-quad-2/AR.parquet but got issues with others at https://beta.source.coop/cholmes/overture/geoparquet-country-quad-2 They're ones that I converted from Overture's parquet distribution, loaded into DuckDB, written out as Parquet and then used geopandas to turn into GeoParquet. 

Error was:
`gpq: error: command.ConvertCmd.Run(): transform generated an unexpected type, got struct, expected struct`

**Comment by tschaub** [comment]
I ran into the same issue before seeing this.  It should be fixed by #84.  `brew update && brew install planetlabs/tap/gpq` to get the latest.  Run `gpq version` to see what version you have.  Version 0.18.0 has the fix.
