### ISSUE TITLE
Report info on row groups in describe?

### ISSUE THREAD

**Issue by cholmes** [planetlabs/gpq#83]
The new 'describe' looks great, the table is super helpful. Was wondering if it might be possible to include information about row groups? I use DuckDB for this, I believe it just reports the total number of row groups, which I think is totally fine if that's easier than figuring out the max number of rows per group.

**Comment by tschaub** [comment]
We could add info about the number of row groups and the number of rows per row group.  The number of rows per group can vary per row group.

**Comment by tschaub** [comment]
I decided to skip the number of rows per group for now.  Mostly awkward to format the table nicely.  Will probably revisit later.
