### ISSUE TITLE
describe and validate remote geoparquet files

### ISSUE THREAD

**Issue by cholmes** [planetlabs/gpq#93]
It'd be awesome if I could run `gpq describe` and `gpq validate` on url's. Doing everything on https would be the default, but if s3:// and others are easy that'd be nice too. I'd like to easily check row groups and validity on big remote resources, so it'd be awesome if it supported this. I feel like Brandon mentioned some go library he was liking for that, but forget where I saw that, so thought I'd put up an issue.

**Comment by tschaub** [comment]
I split off the blob storage support issue into #99 (there we can support reading and writing) and got in support for using input URLs in #98.  You can try it out in the [v0.20.0 release](https://github.com/planetlabs/gpq/releases/tag/v0.20.0) (`brew update && brew install planetlabs/tap/gpq`).
